window.RR_PRODUCTS = [
  {
    "id": "c88cd5d6-3ada-5660-a6e9-30577fea9522",
    "slug": "chocolate-con-arandanos",
    "name": "Chocolate con arándanos - Caja",
    "original_name": "Chocolate con arándanos",
    "packaging": "Caja",
    "category": "Chocolates",
    "description": "Consulta ingredientes y alérgenos con nuestro equipo antes de comprar.",
    "image_url": "images/productos-originales/chocolate-con-arandanos.webp",
    "cacao_percent": 50,
    "gallery_urls": []
  },
  {
    "id": "6b83be70-4e4e-57ed-9dbd-6c8959015875",
    "slug": "chocolate-con-coco",
    "name": "Chocolate con coco - Caja",
    "original_name": "Chocolate con coco",
    "packaging": "Caja",
    "category": "Chocolates",
    "description": "Consulta ingredientes y alérgenos con nuestro equipo antes de comprar.",
    "image_url": "images/productos-originales/chocolate-con-coco.webp",
    "cacao_percent": 50,
    "gallery_urls": []
  },
  {
    "id": "bed63632-47b7-5bdc-9ddb-f7cd5d18a679",
    "slug": "chocomilk",
    "name": "Chocomilk - Caja",
    "original_name": "Chocomilk",
    "packaging": "Caja",
    "category": "Chocolates",
    "description": "Consulta ingredientes y alérgenos con nuestro equipo antes de comprar.",
    "image_url": "images/productos-originales/chocomilk.webp",
    "cacao_percent": 50,
    "gallery_urls": []
  },
  {
    "id": "c0ca1016-a134-5cc0-bda0-164de86ea0e1",
    "slug": "chocolate-capuccino",
    "name": "Chocolate capuccino - Caja",
    "original_name": "Chocolate capuccino",
    "packaging": "Caja",
    "category": "Chocolates",
    "description": "Consulta ingredientes y alérgenos con nuestro equipo antes de comprar.",
    "image_url": "images/productos-originales/chocolate-capuccino.webp",
    "cacao_percent": 45,
    "gallery_urls": []
  },
  {
    "id": "1432f83a-0615-5df9-bb21-3e12231c1227",
    "slug": "chocolate-con-pecana",
    "name": "Chocolate con pecana - Caja",
    "original_name": "Chocolate con pecana",
    "packaging": "Caja",
    "category": "Chocolates",
    "description": "Consulta ingredientes y alérgenos con nuestro equipo antes de comprar.",
    "image_url": "images/productos-originales/chocolate-con-pecana.webp",
    "cacao_percent": 50,
    "gallery_urls": []
  },
  {
    "id": "939e2029-7b7a-5e39-b54f-b834b40e60f5",
    "slug": "chocolate-con-cafe",
    "name": "Chocolate con café - Caja",
    "original_name": "Chocolate con café",
    "packaging": "Caja",
    "category": "Chocolates",
    "description": "Consulta ingredientes y alérgenos con nuestro equipo antes de comprar.",
    "image_url": "images/productos-originales/chocolate-con-cafe.webp",
    "cacao_percent": 50,
    "gallery_urls": []
  },
  {
    "id": "11405220-d2c0-5e60-9f9b-f2df7adc0e92",
    "slug": "chocolate-con-kiwicha",
    "name": "Chocolate con kiwicha - Caja",
    "original_name": "Chocolate con kiwicha",
    "packaging": "Caja",
    "category": "Chocolates",
    "description": "Consulta ingredientes y alérgenos con nuestro equipo antes de comprar.",
    "image_url": "images/productos-originales/chocolate-con-kiwicha.webp",
    "cacao_percent": 50,
    "gallery_urls": []
  },
  {
    "id": "2686fefa-4bd3-51bb-819a-961fb5a173f7",
    "slug": "chocolate-con-almendra",
    "name": "Chocolate con almendra - Caja",
    "original_name": "Chocolate con almendra",
    "packaging": "Caja",
    "category": "Chocolates",
    "description": "Consulta ingredientes y alérgenos con nuestro equipo antes de comprar.",
    "image_url": "images/productos-originales/chocolate-con-almendra.webp",
    "cacao_percent": 50,
    "gallery_urls": []
  },
  {
    "id": "e31b9ba9-8cd8-5ec3-b82c-79b8973a374e",
    "slug": "choco-white",
    "name": "Choco white - Caja",
    "original_name": "Choco white",
    "packaging": "Caja",
    "category": "Chocolates",
    "description": "Consulta ingredientes y alérgenos con nuestro equipo antes de comprar.",
    "image_url": "images/productos-originales/choco-white.webp",
    "cacao_percent": 35,
    "gallery_urls": []
  },
  {
    "id": "a1316422-bcd2-5cdc-854c-21439cb88292",
    "slug": "choco-berries",
    "name": "Choco berries - Caja",
    "original_name": "Choco berries",
    "packaging": "Caja",
    "category": "Chocolates",
    "description": "Con arándanos, aguaymanto y pasas rubias.",
    "image_url": "images/productos-originales/choco-berries.webp",
    "cacao_percent": 70,
    "gallery_urls": []
  },
  {
    "id": "0987d197-205a-5198-a6bb-f8a083a8b4ae",
    "slug": "chocolate-con-naranja",
    "name": "Chocolate con naranja - Caja",
    "original_name": "Chocolate con naranja",
    "packaging": "Caja",
    "category": "Chocolates",
    "description": "Con trozos de naranja deshidratada.",
    "image_url": "images/productos-originales/chocolate-con-naranja.webp",
    "cacao_percent": 60,
    "gallery_urls": []
  },
  {
    "id": "9ac68ab7-363e-5909-afe5-663d5be063c0",
    "slug": "choco-mix-andino",
    "name": "Choco mix andino - Caja",
    "original_name": "Choco mix andino",
    "packaging": "Caja",
    "category": "Chocolates",
    "description": "Con quinua, cañihua y kiwicha.",
    "image_url": "images/productos-originales/choco-mix-andino.webp",
    "cacao_percent": 60,
    "gallery_urls": []
  },
  {
    "id": "5e341141-3160-5dc8-a70d-bba7f557e78a",
    "slug": "chocolate-reforzado-con-garbanzo",
    "name": "Chocolate reforzado con garbanzo - Caja",
    "original_name": "Chocolate reforzado con garbanzo",
    "packaging": "Caja",
    "category": "Chocolates",
    "description": "Revisar el etiquetado: la línea de catálogo contiene distintos endulzantes y no implica ausencia de azúcar.",
    "image_url": "images/productos-originales/chocolate-reforzado-con-garbanzo.webp",
    "cacao_percent": 70,
    "gallery_urls": []
  },
  {
    "id": "90b12b9c-2288-5143-a2d3-738e218bbbff",
    "slug": "chocolate-reforzado-con-maca",
    "name": "Chocolate reforzado con maca - Caja",
    "original_name": "Chocolate reforzado con maca",
    "packaging": "Caja",
    "category": "Chocolates",
    "description": "Revisar el etiquetado: la línea de catálogo contiene distintos endulzantes y no implica ausencia de azúcar.",
    "image_url": "images/productos-originales/chocolate-reforzado-con-maca.webp",
    "cacao_percent": 70,
    "gallery_urls": []
  },
  {
    "id": "b1aaa571-4693-584b-ba2f-cc87b049d305",
    "slug": "chocodark",
    "name": "Chocodark - Caja",
    "original_name": "Chocodark",
    "packaging": "Caja",
    "category": "Chocolates",
    "description": "Revisar el etiquetado: la línea de catálogo contiene distintos endulzantes y no implica ausencia de azúcar.",
    "image_url": "images/productos-originales/chocodark.webp",
    "cacao_percent": 70,
    "gallery_urls": []
  },
  {
    "id": "a1bc2314-d417-5c25-b190-91f78bfec84c",
    "slug": "chocolate-reforzado-con-kiwicha-y-estevia",
    "name": "Chocolate reforzado con kiwicha y estevia - Caja",
    "original_name": "Chocolate reforzado con kiwicha y estevia",
    "packaging": "Caja",
    "category": "Chocolates",
    "description": "Revisar el etiquetado: la línea de catálogo contiene distintos endulzantes y no implica ausencia de azúcar.",
    "image_url": "images/productos-originales/chocolate-reforzado-con-kiwicha-y-estevia.webp",
    "cacao_percent": 90,
    "gallery_urls": []
  },
  {
    "id": "b68ee842-5825-5773-a2f2-8907723982f3",
    "slug": "chocolate-extra-dark",
    "name": "Chocolate extra dark - Caja",
    "original_name": "Chocolate extra dark",
    "packaging": "Caja",
    "category": "Chocolates",
    "description": "Revisar el etiquetado: la línea de catálogo contiene distintos endulzantes y no implica ausencia de azúcar.",
    "image_url": "images/productos-originales/chocolate-extra-dark.webp",
    "cacao_percent": 85,
    "gallery_urls": []
  },
  {
    "id": "0eb97415-7eff-5028-b00d-773db46484cd",
    "slug": "cafe-tueste-frances-500-g",
    "name": "Café tueste francés - Bolsa de 500 g",
    "original_name": "Café tueste francés",
    "packaging": "Bolsa de 500 g",
    "category": "Café",
    "description": "Consulta ingredientes y alérgenos con nuestro equipo antes de comprar.",
    "image_url": "images/productos-originales/cafe-tueste-frances-500-g.webp",
    "cacao_percent": null,
    "gallery_urls": []
  },
  {
    "id": "874e025a-8376-51c5-8884-3b626c8d111c",
    "slug": "cafe-tueste-frances-1-kg",
    "name": "Café tueste francés - Bolsa de 1 kg",
    "original_name": "Café tueste francés",
    "packaging": "Bolsa de 1 kg",
    "category": "Café",
    "description": "Consulta ingredientes y alérgenos con nuestro equipo antes de comprar.",
    "image_url": "images/productos-originales/cafe-tueste-frances-1-kg.webp",
    "cacao_percent": null,
    "gallery_urls": []
  },
  {
    "id": "39f18574-5e95-5c95-a7e2-963b35890f5c",
    "slug": "cafe-tueste-americano-250-g",
    "name": "Café tueste americano - Bolsa de 250 g",
    "original_name": "Café tueste americano",
    "packaging": "Bolsa de 250 g",
    "category": "Café",
    "description": "Consulta ingredientes y alérgenos con nuestro equipo antes de comprar.",
    "image_url": "images/productos-originales/cafe-tueste-americano-250-g.webp",
    "cacao_percent": null,
    "gallery_urls": []
  },
  {
    "id": "dcb947dd-6343-5bd3-b3e0-80737bda4c62",
    "slug": "peru-select-coffee-100-g",
    "name": "Perú Select Coffee - Bolsa de 100 g",
    "original_name": "Perú Select Coffee",
    "packaging": "Bolsa de 100 g",
    "category": "Café",
    "description": "Consulta ingredientes y alérgenos con nuestro equipo antes de comprar.",
    "image_url": "images/productos-originales/peru-select-coffee-100-g.webp",
    "cacao_percent": null,
    "gallery_urls": []
  },
  {
    "id": "a4aa0e4e-3ceb-5221-a0c6-c28bcb789f0a",
    "slug": "peru-select-coffee-250-g",
    "name": "Perú Select Coffee - Bolsa de 250 g",
    "original_name": "Perú Select Coffee",
    "packaging": "Bolsa de 250 g",
    "category": "Café",
    "description": "Consulta ingredientes y alérgenos con nuestro equipo antes de comprar.",
    "image_url": "images/productos-originales/peru-select-coffee-250-g.webp",
    "cacao_percent": null,
    "gallery_urls": []
  },
  {
    "id": "c6dd88aa-0d41-5a81-93ff-031fd0dc50b0",
    "slug": "peru-select-coffee-grano-entero-1-kg",
    "name": "Perú Select Coffee grano entero - Bolsa de 1 kg",
    "original_name": "Perú Select Coffee grano entero",
    "packaging": "Bolsa de 1 kg",
    "category": "Café",
    "description": "Consulta ingredientes y alérgenos con nuestro equipo antes de comprar.",
    "image_url": "images/productos-originales/peru-select-coffee-grano-entero-1-kg.webp",
    "cacao_percent": null,
    "gallery_urls": []
  },
  {
    "id": "7aa1f908-5ebe-5388-96d0-d5dd3d50f069",
    "slug": "cafe-de-especialidad-edicion-limitada",
    "name": "Café de especialidad edición limitada - Lata",
    "original_name": "Café de especialidad edición limitada",
    "packaging": "Lata",
    "category": "Café",
    "description": "Presentación pendiente de confirmar con el equipo.",
    "image_url": "images/productos-originales/cafe-de-especialidad-edicion-limitada.webp",
    "cacao_percent": null,
    "gallery_urls": []
  },
  {
    "id": "a1a1c2b1-7fdb-546b-9ab5-de0266710215",
    "slug": "obelisco-pampa-de-la-quinua-180-g",
    "name": "Obelisco Pampa de la Quinua - Caja de 180 g",
    "original_name": "Obelisco Pampa de la Quinua",
    "packaging": "Caja de 180 g",
    "category": "Chocolates Tradicional",
    "description": "Consulta ingredientes y alérgenos con nuestro equipo antes de comprar.",
    "image_url": "images/productos-originales/obelisco-pampa-de-la-quinua-180-g.webp",
    "cacao_percent": null,
    "gallery_urls": [
      "images/productos-originales/obelisco-pampa-de-la-quinua-escultura.webp"
    ]
  },
  {
    "id": "f7586796-33a3-5922-b866-06d8a3abb05f",
    "slug": "chocolate-huamanguino-300-g",
    "name": "Chocolate huamanguino - Tarrina de 300 g",
    "original_name": "Chocolate huamanguino",
    "packaging": "Tarrina de 300 g",
    "category": "Chocolates Tradicional",
    "description": "Consulta ingredientes y alérgenos con nuestro equipo antes de comprar.",
    "image_url": "images/productos-originales/chocolate-huamanguino-300-g.webp",
    "cacao_percent": null,
    "gallery_urls": []
  },
  {
    "id": "b80eb8a5-c6a4-566c-ac97-7b52237da00c",
    "slug": "chocoandino-220-g",
    "name": "Chocoandino - Caja de 220 g",
    "original_name": "Chocoandino",
    "packaging": "Caja de 220 g",
    "category": "Chocolates Tradicional",
    "description": "Consulta ingredientes y alérgenos con nuestro equipo antes de comprar.",
    "image_url": "images/productos-originales/chocoandino-220-g.webp",
    "cacao_percent": null,
    "gallery_urls": []
  },
  {
    "id": "2df09e63-c454-55ab-ae37-b0dcc70606ac",
    "slug": "pasta-pura-de-cacao-ecologica-life-90-g",
    "name": "Pasta pura de cacao Ecológica Life - Bolsa de 90 g",
    "original_name": "Pasta pura de cacao Ecológica Life",
    "packaging": "Bolsa de 90 g",
    "category": "Pastas",
    "description": "Consulta ingredientes y alérgenos con nuestro equipo antes de comprar.",
    "image_url": "images/productos-originales/pasta-pura-de-cacao-ecologica-life-90-g.webp",
    "cacao_percent": 100,
    "gallery_urls": []
  },
  {
    "id": "be5d5b16-5fc4-576e-ac95-660b156710dc",
    "slug": "chocolate-para-taza-refinado-90-g",
    "name": "Chocolate para taza refinado - Caja de 90 g",
    "original_name": "Chocolate para taza refinado",
    "packaging": "Caja de 90 g",
    "category": "Chocolates Tradicional",
    "description": "Consulta ingredientes y alérgenos con nuestro equipo antes de comprar.",
    "image_url": "images/productos-originales/chocolate-para-taza-refinado-90-g.webp",
    "cacao_percent": 100,
    "gallery_urls": []
  },
  {
    "id": "f08d01cd-6b9e-5f64-9be7-a5f518ecf284",
    "slug": "pasta-de-cacao-organico-500-g",
    "name": "Pasta de cacao orgánico - Bolsa de 500 g",
    "original_name": "Pasta de cacao orgánico",
    "packaging": "Bolsa de 500 g",
    "category": "Pastas",
    "description": "Consulta ingredientes y alérgenos con nuestro equipo antes de comprar.",
    "image_url": "images/productos-originales/pasta-de-cacao-organico-500-g.webp",
    "cacao_percent": 100,
    "gallery_urls": []
  },
  {
    "id": "a61dfd02-0c65-5edf-9889-560958b8372f",
    "slug": "pasta-de-cacao-organico-1-kg",
    "name": "Pasta de cacao orgánico - Bolsa de 1 kg",
    "original_name": "Pasta de cacao orgánico",
    "packaging": "Bolsa de 1 kg",
    "category": "Pastas",
    "description": "Consulta ingredientes y alérgenos con nuestro equipo antes de comprar.",
    "image_url": "images/productos-originales/pasta-de-cacao-organico-1-kg.webp",
    "cacao_percent": 100,
    "gallery_urls": []
  },
  {
    "id": "07ac49d4-304a-5df7-9e91-93541a32eef6",
    "slug": "cacao-en-polvo-150-g",
    "name": "Cacao en polvo - Frasco de 150 g",
    "original_name": "Cacao en polvo",
    "packaging": "Frasco de 150 g",
    "category": "Derivados",
    "description": "Consulta ingredientes y alérgenos con nuestro equipo antes de comprar.",
    "image_url": "images/productos-originales/cacao-en-polvo-150-g.webp",
    "cacao_percent": 100,
    "gallery_urls": []
  },
  {
    "id": "db1524a2-a927-5de8-a837-fabd87bf0be4",
    "slug": "cacao-en-polvo-250-g",
    "name": "Cacao en polvo - Bolsa de 250 g",
    "original_name": "Cacao en polvo",
    "packaging": "Bolsa de 250 g",
    "category": "Derivados",
    "description": "Consulta ingredientes y alérgenos con nuestro equipo antes de comprar.",
    "image_url": "images/productos-originales/cacao-en-polvo-250-g.webp",
    "cacao_percent": 100,
    "gallery_urls": []
  },
  {
    "id": "263e739f-9576-5956-abe4-c1e9c816a724",
    "slug": "mantequilla-de-mani",
    "name": "Mantequilla de maní - Frasco",
    "original_name": "Mantequilla de maní",
    "packaging": "Frasco",
    "category": "Derivados",
    "description": "Consulta ingredientes y alérgenos con nuestro equipo antes de comprar.",
    "image_url": "images/productos-originales/mantequilla-de-mani.webp",
    "cacao_percent": null,
    "gallery_urls": []
  },
  {
    "id": "df186178-bf22-5e52-8b50-43533cf80265",
    "slug": "mantequilla-chocomani",
    "name": "Mantequilla chocomání - Frasco",
    "original_name": "Mantequilla chocomání",
    "packaging": "Frasco",
    "category": "Derivados",
    "description": "Consulta ingredientes y alérgenos con nuestro equipo antes de comprar.",
    "image_url": "images/productos-originales/mantequilla-chocomani.webp",
    "cacao_percent": null,
    "gallery_urls": []
  },
  {
    "id": "c6344afb-cf8c-552d-8a2b-2f4e9c73f03d",
    "slug": "licor-de-cafe-500-ml",
    "name": "Licor de café - Botella de 500 ml",
    "original_name": "Licor de café",
    "packaging": "Botella de 500 ml",
    "category": "Licores",
    "description": "Consulta ingredientes y alérgenos con nuestro equipo antes de comprar.",
    "image_url": "images/productos-originales/licor-de-cafe-500-ml.webp",
    "cacao_percent": null,
    "gallery_urls": []
  },
  {
    "id": "d9104d86-837b-519c-95f1-7dcbe8a0fb70",
    "slug": "licor-coctel-de-cacao-cafe-500-ml",
    "name": "Licor cóctel de cacao café - Botella de 500 ml",
    "original_name": "Licor cóctel de cacao café",
    "packaging": "Botella de 500 ml",
    "category": "Licores",
    "description": "Consulta ingredientes y alérgenos con nuestro equipo antes de comprar.",
    "image_url": "images/productos-originales/licor-coctel-de-cacao-cafe-500-ml.webp",
    "cacao_percent": null,
    "gallery_urls": []
  },
  {
    "id": "d7f5b5ed-f906-5989-bc22-9268a05706d7",
    "slug": "prodigio-bitter-45-g",
    "name": "Prodigio bitter - Caja de 45 g",
    "original_name": "Prodigio bitter",
    "packaging": "Caja de 45 g",
    "category": "Chocolates",
    "description": "Consulta ingredientes y alérgenos con nuestro equipo antes de comprar.",
    "image_url": "images/productos-originales/prodigio-bitter-45-g.webp",
    "cacao_percent": 55,
    "gallery_urls": []
  },
  {
    "id": "a5e44bcc-568d-51ee-bbb7-7ac71f4c3bb3",
    "slug": "prodigio-bitter-con-cafe-45-g",
    "name": "Prodigio bitter con café - Caja de 45 g",
    "original_name": "Prodigio bitter con café",
    "packaging": "Caja de 45 g",
    "category": "Chocolates",
    "description": "Consulta ingredientes y alérgenos con nuestro equipo antes de comprar.",
    "image_url": "images/productos-originales/prodigio-bitter-con-cafe-45-g.webp",
    "cacao_percent": 55,
    "gallery_urls": []
  },
  {
    "id": "586223ba-802f-5d85-9328-93e686d1b65d",
    "slug": "prodigio-leche-y-mani-20-g",
    "name": "Prodigio leche y maní - Envoltura de 20 g",
    "original_name": "Prodigio leche y maní",
    "packaging": "Envoltura de 20 g",
    "category": "Chocolates",
    "description": "Consulta ingredientes y alérgenos con nuestro equipo antes de comprar.",
    "image_url": "images/productos-originales/prodigio-leche-y-mani-20-g.webp",
    "cacao_percent": 40,
    "gallery_urls": []
  },
  {
    "id": "a7c9f81e-4364-53d9-8701-b57526acb9d8",
    "slug": "prodigio-leche-y-kiwicha-20-g",
    "name": "Prodigio leche y kiwicha - Envoltura de 20 g",
    "original_name": "Prodigio leche y kiwicha",
    "packaging": "Envoltura de 20 g",
    "category": "Chocolates",
    "description": "Consulta ingredientes y alérgenos con nuestro equipo antes de comprar.",
    "image_url": "images/productos-originales/prodigio-leche-y-kiwicha-20-g.webp",
    "cacao_percent": 40,
    "gallery_urls": []
  },
  {
    "id": "0501bbb4-a574-570a-86f8-77125ac6e8ab",
    "slug": "prodigio-con-leche-20-g",
    "name": "Prodigio con leche - Envoltura de 20 g",
    "original_name": "Prodigio con leche",
    "packaging": "Envoltura de 20 g",
    "category": "Chocolates",
    "description": "Consulta ingredientes y alérgenos con nuestro equipo antes de comprar.",
    "image_url": "images/productos-originales/prodigio-con-leche-20-g.webp",
    "cacao_percent": 40,
    "gallery_urls": []
  },
  {
    "id": "dbc8139a-f4b4-5da2-a53b-fe883e961a1a",
    "slug": "prodigio-tableta-corazon",
    "name": "Prodigio tableta corazón - Caja",
    "original_name": "Prodigio tableta corazón",
    "packaging": "Caja",
    "category": "Chocolates",
    "description": "Consulta ingredientes y alérgenos con nuestro equipo antes de comprar.",
    "image_url": "images/productos-originales/prodigio-tableta-corazon.webp",
    "cacao_percent": 40,
    "gallery_urls": []
  },
  {
    "id": "3784766b-6d81-5e9d-92cd-806d6372e4c6",
    "slug": "prodigio-coctel-de-frutos",
    "name": "Prodigio cóctel de frutos - Caja",
    "original_name": "Prodigio cóctel de frutos",
    "packaging": "Caja",
    "category": "Chocolates",
    "description": "Consulta ingredientes y alérgenos con nuestro equipo antes de comprar.",
    "image_url": "images/productos-originales/prodigio-coctel-de-frutos.webp",
    "cacao_percent": 40,
    "gallery_urls": []
  },
  {
    "id": "455da9af-8c21-578f-93ae-961374d9ec40",
    "slug": "prodigio-pack-surtido-x-24",
    "name": "Prodigio - Caja de 24 unidades",
    "original_name": "Prodigio",
    "packaging": "Caja de 24 unidades",
    "category": "Chocolates",
    "description": "Consulta ingredientes y alérgenos con nuestro equipo antes de comprar.",
    "image_url": "images/productos-originales/prodigio-pack-surtido-x-24.webp",
    "cacao_percent": 40,
    "gallery_urls": []
  },
  {
    "id": "a2aead86-d5b7-59d1-8caa-b3913ebf6ba7",
    "slug": "grageas-de-cafe-180-g",
    "name": "Grageas de café - Envase cilíndrico de 180 g",
    "original_name": "Grageas de café",
    "packaging": "Envase cilíndrico de 180 g",
    "category": "Grajeados",
    "description": "Consulta ingredientes y alérgenos con nuestro equipo antes de comprar.",
    "image_url": "images/productos-originales/grageas-de-cafe-180-g.webp",
    "cacao_percent": null,
    "gallery_urls": []
  },
  {
    "id": "fb27e5ec-cf2b-5a13-a525-81052dece04c",
    "slug": "grageas-de-arandanos-y-aguaymanto-180-g",
    "name": "Grageas de arándanos y aguaymanto - Envase cilíndrico de 180 g",
    "original_name": "Grageas de arándanos y aguaymanto",
    "packaging": "Envase cilíndrico de 180 g",
    "category": "Grajeados",
    "description": "Consulta ingredientes y alérgenos con nuestro equipo antes de comprar.",
    "image_url": "images/productos-originales/grageas-de-arandanos-y-aguaymanto-180-g.webp",
    "cacao_percent": null,
    "gallery_urls": []
  },
  {
    "id": "473a4412-c794-5802-95d3-2c052528fff4",
    "slug": "grageas-de-cacao-180-g",
    "name": "Grageas de cacao - Envase cilíndrico de 180 g",
    "original_name": "Grageas de cacao",
    "packaging": "Envase cilíndrico de 180 g",
    "category": "Grajeados",
    "description": "Consulta ingredientes y alérgenos con nuestro equipo antes de comprar.",
    "image_url": "images/productos-originales/grageas-de-cacao-180-g.webp",
    "cacao_percent": null,
    "gallery_urls": []
  },
  {
    "id": "aeae09ba-3911-50d3-a762-d0ccc4829cf1",
    "slug": "grageas-de-almendras-180-g",
    "name": "Grageas de almendras - Envase cilíndrico de 180 g",
    "original_name": "Grageas de almendras",
    "packaging": "Envase cilíndrico de 180 g",
    "category": "Grajeados",
    "description": "Consulta ingredientes y alérgenos con nuestro equipo antes de comprar.",
    "image_url": "images/productos-originales/grageas-de-almendras-180-g.webp",
    "cacao_percent": null,
    "gallery_urls": []
  },
  {
    "id": "ee7f0c7d-f850-5fa9-afe9-f5b94b0d14c7",
    "slug": "grageas-de-cafe-40-g",
    "name": "Grageas de café - Bolsa de 40 g",
    "original_name": "Grageas de café",
    "packaging": "Bolsa de 40 g",
    "category": "Grajeados",
    "description": "Consulta ingredientes y alérgenos con nuestro equipo antes de comprar.",
    "image_url": "images/productos-originales/grageas-de-cafe-40-g.webp",
    "cacao_percent": null,
    "gallery_urls": []
  },
  {
    "id": "75491857-7043-5fd5-9f50-5253971665f5",
    "slug": "grageas-de-arandanos-y-aguaymanto-40-g",
    "name": "Grageas de arándanos y aguaymanto - Bolsa de 40 g",
    "original_name": "Grageas de arándanos y aguaymanto",
    "packaging": "Bolsa de 40 g",
    "category": "Grajeados",
    "description": "Consulta ingredientes y alérgenos con nuestro equipo antes de comprar.",
    "image_url": "images/productos-originales/grageas-de-arandanos-y-aguaymanto-40-g.webp",
    "cacao_percent": null,
    "gallery_urls": []
  },
  {
    "id": "e095b4d2-4be9-5216-b392-fd5ffed00527",
    "slug": "grageas-empaque-negro-40-g-por-confirmar",
    "name": "Grageas en empaque negro - Bolsa de 40 g",
    "original_name": "Grageas en empaque negro",
    "packaging": "Bolsa de 40 g",
    "category": "Grajeados",
    "description": "",
    "image_url": "images/productos-originales/grageas-empaque-negro-40-g.webp",
    "cacao_percent": null,
    "gallery_urls": []
  },
  {
    "id": "e9607236-7ce4-54b7-96b6-f6b258397468",
    "slug": "grageas-de-almendras-40-g",
    "name": "Grageas de almendras - Bolsa de 40 g",
    "original_name": "Grageas de almendras",
    "packaging": "Bolsa de 40 g",
    "category": "Grajeados",
    "description": "Consulta ingredientes y alérgenos con nuestro equipo antes de comprar.",
    "image_url": "images/productos-originales/grageas-de-almendras-40-g.webp",
    "cacao_percent": null,
    "gallery_urls": []
  },
  {
    "id": "83a752cf-34b4-5b59-8f8d-5e8dc833d24f",
    "slug": "grageas-de-cafe-100-g",
    "name": "Grageas de café - Bolsa de 100 g",
    "original_name": "Grageas de café",
    "packaging": "Bolsa de 100 g",
    "category": "Grajeados",
    "description": "Consulta ingredientes y alérgenos con nuestro equipo antes de comprar.",
    "image_url": "images/productos-originales/grageas-de-cafe-100-g.webp",
    "cacao_percent": null,
    "gallery_urls": []
  },
  {
    "id": "5c2e12dd-7ff4-58b8-81f8-8a9d55e416b5",
    "slug": "grageas-de-arandanos-y-aguaymanto-100-g",
    "name": "Grageas de arándanos y aguaymanto - Bolsa de 100 g",
    "original_name": "Grageas de arándanos y aguaymanto",
    "packaging": "Bolsa de 100 g",
    "category": "Grajeados",
    "description": "Consulta ingredientes y alérgenos con nuestro equipo antes de comprar.",
    "image_url": "images/productos-originales/grageas-de-arandanos-y-aguaymanto-100-g.webp",
    "cacao_percent": null,
    "gallery_urls": []
  },
  {
    "id": "4919f636-de32-547a-9325-302dac6ee1c9",
    "slug": "grageas-de-cacao-100-g",
    "name": "Grageas de cacao - Bolsa de 100 g",
    "original_name": "Grageas de cacao",
    "packaging": "Bolsa de 100 g",
    "category": "Grajeados",
    "description": "Consulta ingredientes y alérgenos con nuestro equipo antes de comprar.",
    "image_url": "images/productos-originales/grageas-de-cacao-100-g.webp",
    "cacao_percent": null,
    "gallery_urls": []
  },
  {
    "id": "0f8d530f-20d5-58dd-9d73-6092f29ecaa7",
    "slug": "grageas-de-almendras-100-g",
    "name": "Grageas de almendras - Bolsa de 100 g",
    "original_name": "Grageas de almendras",
    "packaging": "Bolsa de 100 g",
    "category": "Grajeados",
    "description": "Consulta ingredientes y alérgenos con nuestro equipo antes de comprar.",
    "image_url": "images/productos-originales/grageas-de-almendras-100-g.webp",
    "cacao_percent": null,
    "gallery_urls": []
  },
  {
    "id": "1d98e98c-cdf9-52b7-9876-05a1e182ec2a",
    "slug": "grageas-de-pasas-borrachas-100-g",
    "name": "Grageas de pasas borrachas - Bolsa de 100 g",
    "original_name": "Grageas de pasas borrachas",
    "packaging": "Bolsa de 100 g",
    "category": "Grajeados",
    "description": "Consulta ingredientes y alérgenos con nuestro equipo antes de comprar.",
    "image_url": "images/productos-originales/grageas-de-pasas-borrachas-100-g.webp",
    "cacao_percent": null,
    "gallery_urls": []
  },
  {
    "id": "ba885cbb-852e-5e1b-99ff-e624f0c7eb6a",
    "slug": "bonomix-pack-x-8",
    "name": "Bonomix - Caja de 8 unidades",
    "original_name": "Bonomix",
    "packaging": "Caja de 8 unidades",
    "category": "Bombones",
    "description": "Precio pendiente de verificación. No habilitar hasta completarlo.",
    "image_url": "images/productos-originales/bonomix-pack-x-8.webp",
    "cacao_percent": 70,
    "gallery_urls": []
  },
  {
    "id": "efcc5b82-c1ad-58ae-ad3f-e347e88427cd",
    "slug": "bombones-con-rellenos-de-jalea",
    "name": "Bombones con rellenos de jalea - Caja",
    "original_name": "Bombones con rellenos de jalea",
    "packaging": "Caja",
    "category": "Bombones",
    "description": "Consulta ingredientes y alérgenos con nuestro equipo antes de comprar.",
    "image_url": "images/productos-originales/bombones-con-rellenos-de-jalea.webp",
    "cacao_percent": 70,
    "gallery_urls": []
  },
  {
    "id": "aeacdce2-6591-537e-8bbe-dcdc6b2059db",
    "slug": "chocotejas-caja-x-10",
    "name": "Chocotejas - Caja de 10 unidades",
    "original_name": "Chocotejas",
    "packaging": "Caja de 10 unidades",
    "category": "Bombones",
    "description": "Consulta ingredientes y alérgenos con nuestro equipo antes de comprar.",
    "image_url": "images/productos-originales/chocotejas-caja-x-10.webp",
    "cacao_percent": 70,
    "gallery_urls": []
  }
];
